version: '3'
services:
  app:
    container_name: dashboard-server
    restart: always
    build: .
    ports:
      - '8080:5100'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --port 27018
    ports:
      - '27018:27018'
